AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data-transformation

  Sample SAM Template for data-transformation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512

Resources:
  DataTransformationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DataTransformationFunction
      Handler: dev.jeffersonfreitas.aws.PostHandler::handleRequest
      Events:
        DataTransformationUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataTransformationApi:
    Description: "API Gateway endpoint URL for Prod stage for DataTransformation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DataTransformationFunction:
    Description: "DataTransformation Lambda Function ARN"
    Value: !GetAtt DataTransformationFunction.Arn
  DataTransformationFunctionIamRole:
    Description: "Implicit IAM Role created for DataTransformation function"
    Value: !GetAtt DataTransformationFunctionRole.Arn
